name: Rust

on:
  push:
    branches: [ "master", "bos" ]
  workflow_dispatch:

permissions:
  contents: write # for committing to gh-pages branch.
  pages: write
  id-token: write
  
concurrency:
  group: "pages"
  cancel-in-progress: false
env:
  CARGO_TERM_COLOR: always
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ubuntu-latest
    # runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable

    - name: Add wasm32-unknown-unknown
      run: rustup target add wasm32-unknown-unknown
      
    - uses: Swatinem/rust-cache@v2
      with:
        cache-all-crates: true
        # key: ${{ matrix.os }}
        cache-on-failure: true
        workspaces: |
          server
          client
        
    - name: Install Trunk
      uses: jetli/trunk-action@v0.5.0
      with:
        version: "latest"
    
    - name: Print Trunk Version
      run: trunk --version

    - name: Install binstall
      uses: cargo-bins/cargo-binstall@main

    - name: Install wasm-bindgen
      run: cargo binstall wasm-bindgen-cli --no-confirm

    - name: Install wasm-pack
      run: cargo binstall wasm-pack --no-confirm

    - name: Install cargo-leptos
      run: cargo binstall cargo-leptos --no-confirm
      
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: SERVER BUILD ${{ matrix.os }}
      run: cd server && cargo build
  
    - name: GAME TEST ${{ matrix.os }}
      run: cd game && wasm-pack test --node
  
    - name: SERVER TEST ${{ matrix.os }}
      run: cd server && cargo test

    - name: CLIENT TEST ${{ matrix.os }}
      run: cd client && cargo test

    - name: CLIENT BUILD ${{ matrix.os }}
      run: cd client && trunk build

    - name: Trunk Build Prod
      run: cd client && trunk build --release --public-url "/Sparganothis"

    - name: Setup Pages
      uses: actions/configure-pages@v4
      with:
        enablement: true
        # token:

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: "./client/target/site"

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4