name: Rust

on:
  push:
    branches: [ "master", "bos" ]
  workflow_dispatch:

permissions:
  contents: write # for committing to gh-pages branch.
  pages: write
  id-token: write
  
concurrency:
  group: "pages"
  cancel-in-progress: false
env:
  CARGO_TERM_COLOR: always
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: nightly

    - name: Add wasm32-unknown-unknown
      run: rustup target add wasm32-unknown-unknown
      
    - uses: Swatinem/rust-cache@v2
    
    - name: Install binstall
      uses: cargo-bins/cargo-binstall@main

    - name: Install wasm-bindgen
      run: cargo binstall wasm-bindgen-cli --no-confirm

    - name: Install wasm-pack
      run: cargo binstall wasm-pack --no-confirm

    - name: Install cargo-leptos
      run: cargo binstall cargo-leptos --no-confirm

    - name: Install Trunk
      uses: jetli/trunk-action@v0.5.0
      with:
        version: "latest"

    - name: Print Trunk Version
      run: trunk --version

    # - name: Trunk Build
    #   run: cd leptris_frontend && trunk build

    - name: Cargo Check
      run: cd leptris_frontend && cargo check

    - name: Trunk Build Prod
      run: cd leptris_frontend && trunk build --release --public-url "/Sparganothis"


    - name: Setup Pages
      uses: actions/configure-pages@v4
      with:
        enablement: true
        # token:

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v4
      with:
        path: "./leptris_frontend/dist"

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
