name: Rust

on:
  push:
    branches: [ "master", "bos" ]
  workflow_dispatch:

# permissions:
#   contents: write # for committing to gh-pages branch.
#   pages: write
#   id-token: write
  
concurrency:
  group: "pages"
  cancel-in-progress: false
env:
  CARGO_TERM_COLOR: always
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable

    - name: Add wasm32-unknown-unknown
      run: rustup target add wasm32-unknown-unknown
      
    - uses: Swatinem/rust-cache@v2
    
    - name: Install binstall
      uses: cargo-bins/cargo-binstall@main

    - name: Install wasm-bindgen
      run: cargo binstall wasm-bindgen-cli --no-confirm

    - name: Install wasm-pack
      run: cargo binstall wasm-pack --no-confirm

    - name: Install cargo-leptos
      run: cargo binstall cargo-leptos --no-confirm

    - name: Cargo Check
      run: time ( bash ./build.sh && bash ./test.sh )